# -*- coding: utf-8 -*-
"""BLIP Image Caption Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPNgpxLzA0_K55-M2MZCRcBLw7mV0EjA

# 🖼️ AI Image Caption Generator using BLIP

## Overview

This project uses the BLIP (Bootstrapping Language-Image Pre-training) transformer model to generate natural language descriptions for images. It demonstrates multimodal AI by combining computer vision and natural language generation.

### Features
- Single-image captioning
- Beam search comparison
- Caption length analysis
- Batch image captioning
- Caption statistics
- CSV export
- Gradio web application
"""

# 1. install libraries
!pip install -q transformers accelerate sentencepiece

# 2. imports
import torch
from PIL import Image
import matplotlib.pyplot as plt

from transformers import (
    BlipProcessor,
    BlipForConditionalGeneration
)

# 3. GPU Check
print("PyTorch Version:", torch.__version__)
print("GPU Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Using Device:", device)

# 4.Load BLIP

processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-image-captioning-base"
)

model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
)

model.to(device)
model.eval()
print(model.config)

import os
os.makedirs("outputs", exist_ok=True)

print("✅ Model Loaded Successfully!")

# 5. Upload Images

from google.colab import files
import os

# Create folders
os.makedirs("images", exist_ok=True)
os.makedirs("outputs", exist_ok=True)

print("Upload one or more images")

uploaded = files.upload()

# Move uploaded images to images folder
for file in uploaded.keys():
    os.rename(file, f"images/{file}")

print(f"✅ {len(uploaded)} image(s) uploaded successfully!")

# 6. Load First Image

folder = "images"

image_files = sorted(os.listdir(folder))

# Use the first uploaded image
image_path = os.path.join(folder, image_files[0])

raw_image = Image.open(image_path).convert("RGB")

print("Using:", image_files[0])

raw_image

# 7. Display image
plt.figure(figsize=(8,8))
plt.imshow(raw_image)
plt.axis("off")
plt.title("Uploaded Image")
plt.show()

#8. preprocess
inputs = processor(
    raw_image,
    return_tensors="pt"
).to(device)
print(inputs.keys())
print(inputs["pixel_values"].shape)

#9. Generate caption and measure inference time
import time

start = time.time()

with torch.no_grad():

    generated_ids = model.generate(
        **inputs,
        max_new_tokens=30
    )

end = time.time()

print(f"Inference Time: {end-start:.3f} seconds")

print("Generated Token IDs:")
print(generated_ids[0])

# 10. Decode  generated captions
caption = processor.decode(
    generated_ids[0],
    skip_special_tokens=True
)

print("Generated Caption:")
print(caption)

# 11. Display Caption

plt.figure(figsize=(8,8))
plt.imshow(raw_image)
plt.axis("off")

plt.title("Generated Caption", fontsize=16)

plt.figtext(
    0.5,
    0.02,
    caption,
    wrap=True,
    ha="center",
    fontsize=14
)

# Save sample prediction
plt.savefig(
    "outputs/sample_prediction.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# 12. Generate Image Caption Function
def generate_caption(
    image,
    max_tokens=40,
    beams=5
):
    """
    Generate a caption for an input image using the BLIP model.

    Parameters:
        image (PIL.Image): Input image.
        max_tokens (int): Maximum number of generated tokens.
        beams (int): Number of beams for beam search.

    Returns:
        str: Generated image caption.
    """

    inputs = processor(
        image,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():

        output = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            num_beams=beams,
            early_stopping=True
        )

    caption = processor.decode(
        output[0],
        skip_special_tokens=True
    )

    return caption

# 13. Test Caption Generation Function

caption = generate_caption(raw_image)

print("Generated Caption using Function:")
print(caption)

#  14. Beam search comparison
for beam in [1,3,5,8]:

    caption = generate_caption(
        raw_image,
        beams=beam
    )

    print(f"Beam {beam}: {caption}")

#  15. Token Length compariosn
for tokens in [10,20,40,60]:

    caption = generate_caption(
        raw_image,
        max_tokens=tokens
    )

    print("="*50)
    print(tokens)
    print(caption)

"""## Batch Processing

Generate captions for multiple images, save them as text files, and export the results to a CSV file for further analysis.
"""

# 16. Batch Captioning

import os

folder = "images"

# Create output folder
os.makedirs("outputs", exist_ok=True)

for file in os.listdir(folder):

    path = os.path.join(folder, file)

    image = Image.open(path).convert("RGB")

    # Generate caption
    caption = generate_caption(image)

    # Save caption as a text file
    filename = os.path.splitext(file)[0]

    with open(f"outputs/{filename}.txt", "w") as f:
        f.write(caption)

    # Display result
    print(file)
    print(caption)
    print()

# 17. Analyze Caption Statistics
import pandas as pd

results = []

folder = "images"

for file in os.listdir(folder):

    path = os.path.join(folder,file)

    image = Image.open(path).convert("RGB")

    caption = generate_caption(image)

    results.append({

        "Image":file,
        "Caption":caption

    })

df = pd.DataFrame(results)

df["Word Count"] = df["Caption"].apply(
    lambda x: len(x.split())
)

print(df)

print()

print("Average Caption Length:",
      df["Word Count"].mean())

print("Longest Caption:",
      df["Word Count"].max())

print("Shortest Caption:",
      df["Word Count"].min())

# 18. save to csv
df.to_csv(
    "outputs/captions.csv",
    index=False
)

print("✅ Results saved to outputs/captions.csv")

# 19. Display batch images
for file in os.listdir(folder):

    path = os.path.join(folder, file)

    image = Image.open(path).convert("RGB")

    caption = generate_caption(image)

    filename = os.path.splitext(file)[0]

    plt.figure(figsize=(6,6))

    plt.imshow(image)

    plt.axis("off")

    plt.title(caption)

    plt.savefig(
        f"outputs/{filename}_result.png",
        dpi=300,
        bbox_inches="tight"
    )

    plt.show()

# 20. Install gradio
!pip install -q gradio

# 21. import gradio
import gradio as gr

def caption_app(image, beams, tokens):

    return generate_caption(
        image,
        beams=int(beams),
        max_tokens=int(tokens)
    )

demo = gr.Interface(

    fn=caption_app,

    inputs=[
        gr.Image(type="pil"),
        gr.Slider(1, 10, step=1, value=5, label="Beam Search"),
        gr.Slider(10, 100, step=1, value=40, label="Max Tokens")
    ],   # <-- Comma here

    outputs="text",

    title="AI Image Caption Generator",

    description="Upload an image to generate a caption."

)

demo.launch()

"""# Future Work

- Fine-tune BLIP on the Flickr8k dataset.
- Compare BLIP Base and BLIP Large.
- Evaluate captions using BLEU, ROUGE, and CIDEr metrics.
- Deploy the application on Hugging Face Spaces.
- Support multilingual image captioning.
"""